on:
  release:
    types: [created]

jobs:
  discord-notify-release:
    if: startsWith(github.event.release.tag_name, '@getlang/get@')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.RELEASE_DISCORD_WEBHOOK_URL }}
          reduce_headings: true
