on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  publish:
    runs-on: ubuntu-latest
    needs: checks
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun --filter @getlang/parser compile
      - uses: changesets/action@v1
        with:
          publish: bun pub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
